<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from reportorganizer/xml/schema/CRM/Reportorganizer/ReportOrganizer.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:444f561c1f626d7a6d8b43fedde50326)
 */
use CRM_Reportorganizer_ExtensionUtil as E;

/**
 * Database access object for the ReportOrganizer entity.
 */
class CRM_Reportorganizer_DAO_ReportOrganizer extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_report_instance_organizer';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique ReportOrganizer ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to CiviCRM Component
   *
   * @var int
   */
  public $component_id;

  /**
   * Pseudo FK to civicrm_option.value WHERE option_group = report_template
   *
   * @var int
   */
  public $section_id;

  /**
   * FK to CiviCRM Report Instance
   *
   * @var int
   */
  public $report_instance_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_report_instance_organizer';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Report Organizers') : E::ts('Report Organizer');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'component_id', 'civicrm_component', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'report_instance_id', 'civicrm_report_instance', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique ReportOrganizer ID'),
          'required' => TRUE,
          'where' => 'civicrm_report_instance_organizer.id',
          'table_name' => 'civicrm_report_instance_organizer',
          'entity' => 'ReportOrganizer',
          'bao' => 'CRM_Reportorganizer_DAO_ReportOrganizer',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'component_id' => [
          'name' => 'component_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to CiviCRM Component'),
          'where' => 'civicrm_report_instance_organizer.component_id',
          'table_name' => 'civicrm_report_instance_organizer',
          'entity' => 'ReportOrganizer',
          'bao' => 'CRM_Reportorganizer_DAO_ReportOrganizer',
          'localizable' => 0,
          'FKClassName' => 'CRM_Core_DAO_Component',
          'add' => NULL,
        ],
        'section_id' => [
          'name' => 'section_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Pseudo FK to civicrm_option.value WHERE option_group = report_template'),
          'where' => 'civicrm_report_instance_organizer.section_id',
          'table_name' => 'civicrm_report_instance_organizer',
          'entity' => 'ReportOrganizer',
          'bao' => 'CRM_Reportorganizer_DAO_ReportOrganizer',
          'localizable' => 0,
          'add' => NULL,
        ],
        'report_instance_id' => [
          'name' => 'report_instance_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to CiviCRM Report Instance'),
          'where' => 'civicrm_report_instance_organizer.report_instance_id',
          'table_name' => 'civicrm_report_instance_organizer',
          'entity' => 'ReportOrganizer',
          'bao' => 'CRM_Reportorganizer_DAO_ReportOrganizer',
          'localizable' => 0,
          'FKClassName' => 'CRM_Report_DAO_ReportInstance',
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'report_instance_organizer', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'report_instance_organizer', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'UI_component_id_section_id_report_instance_id' => [
        'name' => 'UI_component_id_section_id_report_instance_id',
        'field' => [
          0 => 'component_id',
          1 => 'section_id',
          2 => 'report_instance_id',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_report_instance_organizer::1::component_id::section_id::report_instance_id',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
